---
name: Catalyst-Plugin-Authentication-CDBI-Basic
version: 0.02
author:
  - 'Daisuke Murase E<lt>typester@cpan.orgE<gt>'
abstract: (DEPRECATED) Basic Authorization with Catalyst
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.33
  Catalyst::Plugin::Authentication::CDBI: 0
  MIME::Base64: 0
  perl: 5.6.0
provides:
  Catalyst::Plugin::Authentication::CDBI::Basic:
    file: lib/Catalyst/Plugin/Authentication/CDBI/Basic.pm
    version: 0.02
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
